### ISSUE TITLE
Please create separate repositories

### ISSUE THREAD

**Issue by tarsius** [kensanata/elisp#3]
@kensanata Could you please create separate repositories for packages that have nothing to do with one another? That would help users who install packages as git submodules and would also allow me to add the packages to the Emacsmirror. I am currently working (once more) to mirror all the packages that are available from Melpa. `rcirc-color` and `rcirc-controls` are available from Melpa but not yet the Emacsmirror - so if you are inclined to split up this repository, but do not have the time to do it all now, then maybe you should start with those. (Putting all `rcirc` libraries into a single repository would work, though I would prefer if libraries that can be used independently also lived in independent repositories.)

**Comment by kensanata** [comment]
https://github.com/kensanata/rcirc-color

**Comment by kensanata** [comment]
https://github.com/aaron-em/rcirc-styles.el replaces rcirc-colors.el, I think.

**Comment by kensanata** [comment]
Any other package you want to add, specifically? I'll be happy to create more repos if anybody asks for them, but I don't think these files are popular...

**Comment by tarsius** [comment]
> Any other package you want to add, specifically?

No (that were all the packages from this repository which made it to Melpa, I believe), but what about `rcirc-controls`?

**Comment by kensanata** [comment]
Sorry, my mistake. rcirc-styles.el replaces rcirc-controls.el.

**Comment by tarsius** [comment]
No problem. And thanks!
